export PATH="$HOME/.local/bin:/usr/local/bin:${PATH}"
# export EDITOR="emacsclient -t"
# export VISUAL="emacsclient -c -a emacs"
# export ALTERNATE_EDITOR=""
# alias em="emacsclient -t"
export HISTTIMEFORMAT="%d/%m/%Y %T "
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
PS1='\[\e[1;32m\]\u@\[\e[0m\]\h:\W\[\e[1;32m\]\$\[\e[0m\] '
alias bimbo='ssh giovenko@192.168.178.37'
alias vim='nvim'
