brew uninstall neovim
brew uninstall libtermkey
brew uninstall libuv
brew uninstall libvterm
brew uninstall luajit
brew uninstall luarocks
brew uninstall lua
brew uninstall msgpack
brew uninstall unibilium
brew uninstall pkg-config
rm -rf ~/.vim/
rm -rf ~/.config/nvim/
rm -rf ~/.local/share/nvim/
